apiVersion: v1
kind: Pod
metadata:
  name: kube-controller-manager
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
    - name: kube-controller-manager
      image: registry.k8s.io/kube-controller-manager:v1.30.0
      command:
        - kube-controller-manager
        - --kubeconfig=/etc/kubernetes/kubeconfig
        - --service-account-private-key-file=/etc/kubernetes/sa.key
        - --root-ca-file=/etc/kubernetes/ca.crt
        - --cluster-signing-cert-file=/etc/kubernetes/ca.crt
        - --cluster-signing-key-file=/etc/kubernetes/ca.key
        - --controllers=*,bootstrapsigner,tokencleaner
        - --leader-elect=false
        - --use-service-account-credentials=true
        - --bind-address=0.0.0.0
      volumeMounts:
        - name: config
          mountPath: /etc/kubernetes
  volumes:
    - name: config
      hostPath:
        path: /var/lib/kubelet
